// Code generated by MockGen. DO NOT EDIT.
// Source: control/controlHelper.go

// Package mock_control is a generated GoMock package.
package mock_control

import (
	reflect "reflect"

	models "github.com/akuldr67/Boolean/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepoInterface is a mock of RepoInterface interface
type MockRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepoInterfaceMockRecorder
}

// MockRepoInterfaceMockRecorder is the mock recorder for MockRepoInterface
type MockRepoInterfaceMockRecorder struct {
	mock *MockRepoInterface
}

// NewMockRepoInterface creates a new mock instance
func NewMockRepoInterface(ctrl *gomock.Controller) *MockRepoInterface {
	mock := &MockRepoInterface{ctrl: ctrl}
	mock.recorder = &MockRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepoInterface) EXPECT() *MockRepoInterfaceMockRecorder {
	return m.recorder
}

// GetAllBooleansHelper mocks base method
func (m *MockRepoInterface) GetAllBooleansHelper(bools *[]models.Boolean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBooleansHelper", bools)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAllBooleansHelper indicates an expected call of GetAllBooleansHelper
func (mr *MockRepoInterfaceMockRecorder) GetAllBooleansHelper(bools interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBooleansHelper", reflect.TypeOf((*MockRepoInterface)(nil).GetAllBooleansHelper), bools)
}

// CreateBooleanHelper mocks base method
func (m *MockRepoInterface) CreateBooleanHelper(newBool *models.Boolean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooleanHelper", newBool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooleanHelper indicates an expected call of CreateBooleanHelper
func (mr *MockRepoInterfaceMockRecorder) CreateBooleanHelper(newBool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooleanHelper", reflect.TypeOf((*MockRepoInterface)(nil).CreateBooleanHelper), newBool)
}

// GetBooleanByIDHelper mocks base method
func (m *MockRepoInterface) GetBooleanByIDHelper(boolean *models.Boolean, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooleanByIDHelper", boolean, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetBooleanByIDHelper indicates an expected call of GetBooleanByIDHelper
func (mr *MockRepoInterfaceMockRecorder) GetBooleanByIDHelper(boolean, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooleanByIDHelper", reflect.TypeOf((*MockRepoInterface)(nil).GetBooleanByIDHelper), boolean, id)
}

// UpdateBooleanHelper mocks base method
func (m *MockRepoInterface) UpdateBooleanHelper(oldBool *models.Boolean, newBool models.Boolean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooleanHelper", oldBool, newBool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBooleanHelper indicates an expected call of UpdateBooleanHelper
func (mr *MockRepoInterfaceMockRecorder) UpdateBooleanHelper(oldBool, newBool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooleanHelper", reflect.TypeOf((*MockRepoInterface)(nil).UpdateBooleanHelper), oldBool, newBool)
}

// DeleteBooleanHelper mocks base method
func (m *MockRepoInterface) DeleteBooleanHelper(boolean *models.Boolean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooleanHelper", boolean)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooleanHelper indicates an expected call of DeleteBooleanHelper
func (mr *MockRepoInterfaceMockRecorder) DeleteBooleanHelper(boolean interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooleanHelper", reflect.TypeOf((*MockRepoInterface)(nil).DeleteBooleanHelper), boolean)
}
